version: 2.1

jobs:
    test:
        docker:
            - image: abeljosesanchez/beziervice
        steps:
            - checkout
            - run: make test

workflows:
    test_in_docker:
        jobs:
            - test