[package]
name = "beziervice"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mathru = "0.13"
pretty_assertions = "1.2.1"
